# Generated by Django 4.2.7 on 2025-09-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(help_text='Event description')),
                ('date', models.DateTimeField(help_text='Event date and time')),
                ('location', models.CharField(help_text='Event location', max_length=200)),
                ('image', models.ImageField(help_text='Event image', upload_to='events/')),
                ('event_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', help_text='Event type', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('registration_url', models.URLField(blank=True, help_text='Event registration URL')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees', null=True)),
                ('current_attendees', models.PositiveIntegerField(default=0, help_text='Current number of registered attendees')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the event was last updated')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
    ]
