# Generated by Django 4.2.7 on 2025-09-07 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Article content')),
                ('excerpt', models.TextField(help_text='Short article summary', max_length=300)),
                ('image', models.ImageField(help_text='Article featured image', upload_to='news/')),
                ('author', models.CharField(help_text='Article author', max_length=100)),
                ('category', models.CharField(choices=[('ai_news', 'AI News'), ('company_news', 'Company News'), ('technology', 'Technology'), ('industry_insights', 'Industry Insights'), ('case_studies', 'Case Studies'), ('announcements', 'Announcements'), ('other', 'Other')], default='other', help_text='Article category', max_length=50)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the article is published')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the article was published')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the article was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the article was last updated')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times article was viewed')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the article', max_length=500)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
