# Generated by Django 4.2.7 on 2025-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Article featured image (optional)', upload_to='news/'),
        ),
    ]
