# Generated by Django 4.2.7 on 2025-09-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title', max_length=200)),
                ('image', models.ImageField(help_text='Photo file', upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Photo description')),
                ('category', models.CharField(choices=[('events', 'Events'), ('team', 'Team'), ('office', 'Office'), ('promotional', 'Promotional'), ('conferences', 'Conferences'), ('awards', 'Awards'), ('other', 'Other')], default='other', help_text='Photo category', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the photo was last updated')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
