# Generated by Django 4.2.7 on 2025-09-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('company', models.CharField(help_text="Customer's company name", max_length=100)),
                ('country', models.CharField(help_text="Customer's country", max_length=100)),
                ('job_title', models.CharField(help_text="Customer's job title", max_length=100)),
                ('job_details', models.TextField(help_text='Detailed description of job requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the inquiry was submitted')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the inquiry has been processed')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the inquiry')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
