# Generated by Django 4.2.7 on 2025-09-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Service description')),
                ('short_description', models.CharField(help_text='Short service description for cards', max_length=300)),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fas fa-robot')", max_length=50)),
                ('category', models.CharField(choices=[('ai_solutions', 'AI Solutions'), ('automation', 'Automation'), ('data_analytics', 'Data Analytics'), ('machine_learning', 'Machine Learning'), ('consulting', 'Consulting'), ('integration', 'Integration'), ('support', 'Support'), ('other', 'Other')], default='other', help_text='Service category', max_length=50)),
                ('features', models.TextField(default='[]', help_text='JSON string of features list')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_active', models.BooleanField(default=True, help_text='Whether service is currently offered')),
                ('price_starting_from', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for the service', max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', help_text='Currency code', max_length=3)),
                ('image', models.ImageField(blank=True, help_text='Service image', upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the service was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the service was last updated')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
    ]
