# Generated by Django 4.2.7 on 2025-09-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Solution title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed solution description')),
                ('short_description', models.CharField(help_text='Short solution description for cards', max_length=300)),
                ('category', models.CharField(choices=[('ai_solutions', 'AI Solutions'), ('automation', 'Automation'), ('data_analytics', 'Data Analytics'), ('machine_learning', 'Machine Learning'), ('fintech', 'FinTech'), ('iot', 'IoT'), ('safety', 'Safety & Compliance'), ('other', 'Other')], default='other', help_text='Solution category', max_length=50)),
                ('features', models.TextField(default='[]', help_text='JSON string of features list')),
                ('client_name', models.CharField(blank=True, help_text='Client name (if applicable)', max_length=200)),
                ('project_duration', models.CharField(blank=True, help_text="Project duration (e.g., '3 months', '6 weeks')", max_length=100)),
                ('technologies_used', models.TextField(default='[]', help_text='JSON string of technologies used')),
                ('image', models.ImageField(blank=True, help_text='Solution image', upload_to='past_solutions/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_published', models.BooleanField(default=True, help_text='Whether solution is published')),
                ('completion_date', models.DateField(help_text='When the solution was completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the solution was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the solution was last updated')),
            ],
            options={
                'verbose_name': 'Past Solution',
                'verbose_name_plural': 'Past Solutions',
                'ordering': ['-completion_date'],
            },
        ),
    ]
