# Generated by Django 4.2.7 on 2025-09-15 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, unique=True)),
                ('inquiries_total', models.PositiveIntegerField(default=0)),
                ('inquiries_pending', models.PositiveIntegerField(default=0)),
                ('inquiries_last7', models.PositiveIntegerField(default=0)),
                ('articles_total', models.PositiveIntegerField(default=0)),
                ('articles_published', models.PositiveIntegerField(default=0)),
                ('articles_draft', models.PositiveIntegerField(default=0)),
                ('articles_featured', models.PositiveIntegerField(default=0)),
                ('events_total', models.PositiveIntegerField(default=0)),
                ('events_upcoming', models.PositiveIntegerField(default=0)),
                ('events_past', models.PositiveIntegerField(default=0)),
                ('testimonials_total', models.PositiveIntegerField(default=0)),
                ('testimonials_approved', models.PositiveIntegerField(default=0)),
                ('testimonials_featured', models.PositiveIntegerField(default=0)),
                ('services_total', models.PositiveIntegerField(default=0)),
                ('services_active', models.PositiveIntegerField(default=0)),
                ('services_featured', models.PositiveIntegerField(default=0)),
                ('photos_total', models.PositiveIntegerField(default=0)),
                ('photos_featured', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
