# Generated by Django 4.2.7 on 2025-09-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's name", max_length=100)),
                ('company', models.CharField(help_text="Customer's company", max_length=100)),
                ('job_title', models.CharField(blank=True, help_text="Customer's job title", max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Customer rating (1-5 stars)')),
                ('content', models.TextField(help_text='Testimonial content')),
                ('image', models.ImageField(blank=True, help_text='Customer photo (optional)', upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether testimonial is approved for display')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the testimonial was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the testimonial was last updated')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
