# Generated by Django 4.2.7 on 2025-09-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_pastsolution'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service being rated (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
